import = ['~/.config/alacritty/color.toml']

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "full"
dynamic_padding = false

[window.padding]
x = 5
y =  5

[font]
size = 16.0

[font.normal]
family = "CaskaydiaCove NFM"
style = "Regular"

[font.bold]
family = "CaskaydiaCove NFM"
style = "Medium"

[font.italic]
family = "CaskaydiaCove NFM"
style = "Italic"

[font.bold_italic]
family = "CaskaydiaCove NFM"
style = "Medium Italic"
